#!/bin/bash

# Variables
rofi_command="rofi -theme $HOME/.config/polybar/scripts/sysmenu/themes/powermenu_alt.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Opciones
shutdown=" Apagar"
reboot=" Reiniciar"
lock=" Blokear"
logout=" Secion"

# Horden
options="$shutdown\n$reboot\n$lock\n$logout"

# Ejecunion
chosen="$(echo -e "$options" | $rofi_command -p "$uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        i3lock
        ;;
    $logout)
        kill -9  -1
        ;;
esac
