#!/bin/bash

rofi_command="rofi -theme $HOME/.config/polybar/scripts/sysmenu/inferior/themes/powermenu_alt.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown=" Apagar"
reboot=" Reiniciar"
lock=" Blokear"
logout=" Secion"

# Variable passed to rofi
options="$shutdown\n$reboot\n$lock\n$logout"

chosen="$(echo -e "$options" | $rofi_command -p "$uptime" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        i3lock
        ;;
    $logout)
        kill -9  -1
        ;;
esac
